In [83]:
from IPython.display import Image
from IPython.core.display import HTML 
import numpy as np

# **Welcome to the Kresge Library's Introduction to Data Visualization**
### **By Vincent Lao and Daniel del Carpio**
##### In Collaboration with the Division of Data Science's [Data Peer Consulting](https://data.berkeley.edu/ds-peer-consulting)

# Vincent Lao 
![Vincent](https://data.berkeley.edu/sites/default/files/styles/width_400/public/general/vincent-headshot-2_-_vincent_lao_1_0.jpg?itok=98MmRkiK&timestamp=1599233937)

Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Data Science and Statistics
    👨🏼‍🏫 Past Tutor for Data100, Current Reader for Stat151a
    🏢 Previously interned with the U.S. Naval Research Laboratory & researched at Osaka Univeristy
    📊 Joined the Data Peer Consulting team in Fall 2019

How to Reach/Stalk Me:

    📮 Email: vincent.lao@berkeley.edu

# Daniel del Carpio
![Carlos](https://data.berkeley.edu/sites/default/files/styles/width_400/public/img_3245_-_carlos_ortega.jpeg?itok=6cdS9XWS&timestamp=1599261924)
Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Cognitive Science, interest in NLP
    👨🏼‍🏫 I love to teach
    🏢 Previously worked for U.S. Census Bureau, ICSI, Data 8 Course Staff
    📊 Joined the Data Peer Consulting team in Fall '18

How to Reach/Stalk Me:

    📮 Email: ceos@berkeley.edu
    👨🏼‍💻 Github: @SoyCarlos

## Summary of Last Workshop 

# What is Numpy?

![Python Logo](images/python-logo.png)

From [Python's Official Site](https://www.python.org/doc/essays/blurb/):


> Python is an **interpreted**, **object-oriented**, **high-level programming language** with dynamic semantics. Its high-level built in data structures, combined with **dynamic typing** and **dynamic binding**, make it very attractive for **Rapid Application Development**, as well as for use as a **scripting** or glue language to connect existing components together. Python's simple, **easy to learn syntax** emphasizes **readability** and therefore reduces the cost of program maintenance. Python supports **modules** and **packages**, which encourages program modularity and code reuse. The Python interpreter and the extensive standard library are available in source or binary form without charge for all major platforms, and can be freely distributed. 

In layman terms, Python is:
- A Programming Language
- Easy to read
- Easy to learn
- Easy to use with other pre-existing programs
- Quick to adapt to any use-cases
- Open-Source

Modules, packages, and libraries are collections of re-usable code used to improve the interoperability of code and the effiency of programmers.

Examples:
- [Pandas](https://pandas.pydata.org/) - Today's package of choice for data analysis
- [Numpy](https://numpy.org/) - Scientific Computing
- [Biopython](https://biopython.org/) - Biological Computation
- [Astropy](https://www.astropy.org/index.html) - Astronomy
- [Nilearn](http://nilearn.github.io/) - Neuroimaging
- [SageMath](https://www.sagemath.org/) - Collection of Math Packages (Elementary, Algebra, Calculus, Number Theory, etc)


### Reference Sheets for today!
Links updated as of 9/29/20  
- [NumPy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)  
- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)  
- [Matplotlib Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Matplotlib_Cheat_Sheet.pdf)  
- [Seaborn Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Seaborn_Cheat_Sheet.pdf)

![NumPy+Pandas Logo](images/numpypandas-logo.png)

# NumPy Fundamentals
NumPy stands for "Numerical Python". What this means is that Numpy is a package used for fast, efficient numerical calculations in Python. Numpy uses what we will call ***Numpy Arrays***, which are very similar to Python lists, but have a couple of key differences that we will take a look at.  

To use the Numpy package (or any other package), we must always import it into whatever text editor (program used for coding, e.g. Jupyter Notebook) that we are using.

In [84]:
# the conventional NumPy import statement
import numpy as np

We can now use the NumPy package with the shorthand `np`! We access various functions inside this package with `np.function(*arguments)`, where function() is the function you would like to use.

[Jump to Key Difference 3](#kd3)  
[Jump to Numpy Functions](#npfuncs)

In [85]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Without further ado, let's talk about the differences between NumPy arrays and Python lists!  

---

**Key Difference 1:** They have different data types.

In [86]:
# Python list
# The notation to create one is using square brackets. You can create an empty one like so:
list1 = []
type(list1)

list

In [87]:
# Numpy array
# Notice that by passing a Python list into the np.array() function as an argument, it turns it into a NumPy array!
array1 = np.array([])
type(array1)

numpy.ndarray

**Key Difference 2:** Python lists can contain any kind of data type, and keeps them the way they are. However, NumPy objects can only contain data of the same type.

In [88]:
list2 = ['any', 123, 'kind', 456, 'of', 123/456, 'data', True, 'type']
list2

['any', 123, 'kind', 456, 'of', 0.26973684210526316, 'data', True, 'type']

In [89]:
array2 = np.array(list2)
array2

array(['any', '123', 'kind', '456', 'of', '0.26973684210526316', 'data',
       'True', 'type'], dtype='<U19')

In [90]:
array2[1], list2[1]

('123', 123)

In [91]:
type(array2[1]), type(list2[1])

(numpy.str_, int)

How does NumPy determine which data type to turn everything into then? 

Out of the primitive* data types, there's a "data type hierarchy" so to speak. NumPy will turn all the entries into the most complex data type that it finds in the array. The hierarchy is as follows, from least complex to most complex:
- **Boolean < Integer < Float < String**

\**primitive data types: boolean - true/false, integer, float - decimal numbers, string - letters*

In [92]:
# some more examples
np.array([True, False, 1, 2, 3, 1.1, 2.2, 3.3]), np.array([True, False, 1, 2, 3])

(array([1. , 0. , 1. , 2. , 3. , 1.1, 2.2, 3.3]), array([1, 0, 1, 2, 3]))

- True values turn into 1
- False values turn into 0
- Integers get a decimal point
- Floats turn into strings, indicated by the quotation marks around them

**Key Difference 3 [Very Important] :** Numerical operations with Python lists has different behavior than adding NumPy arrays.  <a class="anchor" id="kd3"></a>

In [93]:
list3 = [1, 2, 3]
list4 = [1, 2, 3]
list3 + list4

[1, 2, 3, 1, 2, 3]

In [94]:
list3 - list4 # error is expected

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
list3 * list4 # error is expected

In [ ]:
list3 / list4 # error is expected

In [ ]:
# note: we are not reassigning this value to list3, so the result we see printed out under this cell is not permanent
list3 + [4] 

In [ ]:
# What if we put strings inside the Python lists?
string_list1 = ['test', '1', '2', '3']
string_list2 = ['test', '4', '5', '6']
string_list1 + string_list2

---

Now with Numpy Arrays:

In [ ]:
array3 = np.array(list3) # Q: What is happening here? A: Think about replacing "list3" with the value assigned to it!
array4 = np.array(list4)
array3 + array4

In [ ]:
array3 + 10 # automatically performs element-wise arithmetic: [1+10, 2+10, 3+10]

In [ ]:
array3 * 10 # [1*10, 2*10, 3*10]

In [ ]:
array3 - array4

In [ ]:
array3 * array4

In [ ]:
array3 / array4 # notice it automatically converts things to floats when we divide!

In [ ]:
array3 ** array4 # ** denotes exponents, which also works for NumPy!

In [97]:
# What if we put strings inside the NumPy arrays? [Error expected]
string_array1 = np.array(['test', '1', '2', '3'])
string_array2 = np.array(['test', '4', '5', '6'])
string_array1 + string_array2

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U4'), dtype('<U4')) -> dtype('<U4')

In short, there are some limitations to both. 
- Python lists can hold multiple data types at a time, while NumPy arrays can only hold one data type at a time
- Adding Python lists *concatenates* them, while adding NumPy arrays performs element-wise addition
- Other operations on Python lists don't work, but any numerical operation works element-wise with NumPy arrays

---

Now, let's learn some very common NumPy array functions besides `np.array()`!

### Commonly Used NumPy Functions <a class="anchor" id="npfuncs"></a>
Here are the corresponding NumPy documentations for reference:
- [np.append](https://numpy.org/doc/stable/reference/generated/numpy.append.html)
- [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
- [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

Alternatively, when your typing line is hovering over a function, you can click `shift` + `tab` to open up the same documentation in Jupyter Notebook. Handy!

---
Since addition doesn't allow us to *concatenate* two NumPy arrays, we have to have another way to do so.
`np.append` does exactly that.

In [100]:
# re-print the arrays for reference
array5 = np.array([4,5,6])
array4, array5, string_array1

(array([1, 2, 3]),
 array([4, 5, 6]),
 array(['test', '1', '2', '3'], dtype='<U4'))

In [103]:
# np.append
np.append(array4, array5)

array([1, 2, 3, 4, 5, 6])

In [104]:
# The data types still change accordingly after appending
np.append(array4, string_array1)

array(['1', '2', '3', 'test', '1', '2', '3'], dtype='<U11')

---

`np.arange` creates a list of numbers based on the arguments you pass in.

In [105]:
# np.arange(start value, stop value, step size); stop value is not included!
# default start is 0, stop value is required (no default), default step size is 1 
np.arange(5)

array([0, 1, 2, 3, 4])

In [109]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [107]:
np.arange(0,5,2)

array([0, 2, 4])

In [110]:
np.arange(2,6,2) # Before running this, try to predict what it will print out!

array([2, 4])

---

`np.linspace` creates a list of `n` values that are perfectly evenly spaced between `start value` and `stop value`, where `n = number of values`.

This is very handy for when you need to create visualizations, and you want your tick marks or bins to be perfectly spaced.

In [112]:
# np.linspace(start value, stop value, number of values); the stop value IS included
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [113]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [114]:
# "number of values" has a default of 50
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

---

There are many functions that calculate various descriptive statistics as well. Note that you can pass in either a NumPy array or a Python list, as its argument.

- np.min
- np.max
- np.sum
- np.mean
- np.median
- np.std
- np.percentile

In [115]:
numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
np.min(numbers), np.max(numbers), np.sum(numbers)

(1, 233, 609)

In [116]:
np.mean(numbers), np.std(numbers), np.median(numbers), np.percentile(numbers, 50) # 50th percentile = median

(46.84615384615385, 67.54582052075824, 13.0, 13.0)

## Pandas Fundamentals 
<div>
<img src="images/pandas-logo.jpeg" width="400" style="float:left"/>
</div>

We'll just go ahead and continue into Pandas!

Pandas stands for "**Pan**el **Da**ta" (I know, not as good as NumPy). This is just referring to the tables, or **dataframes**, that Pandas works with. Dataframes are the most common and intuitive way for both humans and computers to organize data.

Being able to manipulate those dataframes is crucial for data scientists to be able to clean up their data in a way that is usable for analysis. 

This is where Pandas comes in.

We will talk about two main methods of cleaning our data to get ready for visualization:
1. [Filtering](#filtering)
2. [Grouping](#grouping)

But before learning the more techinical stuff, here's a quick introduction to Pandas.

In [13]:
# the conventional Pandas import statement
import pandas as pd

There are 3 main functions for Pandas in the [data science life cycle](https://towardsdatascience.com/data-science-life-cycle-101-for-dummies-like-me-e66b47ad8d8f).

1. Reading in data
2. Summarizing the data
3. Cleaning the data  
    a. Stratify by grouping and filtering for certain subsets of the dataframe  
    b. Fill in or remove missing data  
    c. Combine various dataframes into a single dataframe  

For this workshop, we'll focus on the knowledge of Pandas that is helpful for creating great visualizations.

First, let's introduce the DataFrame and Series data types.  

A DataFrame is like a 2D table of information. Each row is called a **record or observation** because rows typically represent some real life event or object. And each column is called a **feature** because it's an aspect of the real life event or object.

In [117]:
# Pandas reads in data and creates a DataFrame object of them
lib_traffic = pd.read_csv('data/HourlyTraffic-2019-12-11.csv')

# dataframe.head() returns the first 5 rows and all the columns of the dataframe
lib_traffic.head()

Date-Time       Region      Facility   Entrance  Entries  Exits
0  12/11/19 12:00 AM          NaN           NaN       TEST      0.0    0.0
1  12/11/19 12:00 AM  UC Berkeley   AHC Library   AHC Back      0.0    0.0
2  12/11/19 12:00 AM  UC Berkeley   AHC Library  AHC Front      0.0    0.0
3  12/11/19 12:00 AM  UC Berkeley  ANTH Library       ANTH      0.0    0.0
4  12/11/19 12:00 AM  UC Berkeley  BANC Library   Bancroft      0.0    0.0

In the case of this dataset, each record represents an event -- the traffic of a specific location at a specific time.  
Each column represents a piece of information regarding each record.

In [119]:
# a sanity check for the data type of lib_traffic
type(lib_traffic)

pandas.core.frame.DataFrame

To grab certain parts of the dataframe, we can use slicing notation, similar to how we slice into Python lists or NumPy arrays. For a dataframe inside the variable `df`, we can slice like this:
```
df['column_name']
```
and it will give us a **Series**. <a class="anchor" id="series"></a>

A **Series** is a special data type that represents the column of a dataframe. A **Series** works very similar to a NumPy because it is *literally* a NumPy array with some extra functions built into it. More information about **Series** is always a Google search away, if you are interested in learning more about those extra functions.

[Back to Exercise 1](#ex1)

In [122]:
# grabs the Entries column as a Series from the dataframe
lib_traffic['Entries'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Entries, dtype: float64

In [123]:
# a sanity check for the data type of the Entries column
type(lib_traffic['Entries'])

pandas.core.series.Series

In [124]:
# Series behaving like a NumPy array
lib_traffic['Entries'][10:20]

10    182.0
11      5.0
12      0.0
13      0.0
14      0.0
15      4.0
16      3.0
17      0.0
18      5.0
19      2.0
Name: Entries, dtype: float64

In [125]:
lib_traffic['Entries'][10:20] * 2

10    364.0
11     10.0
12      0.0
13      0.0
14      0.0
15      8.0
16      6.0
17      0.0
18     10.0
19      4.0
Name: Entries, dtype: float64

## Filtering with Pandas <a class="anchor" id="filtering"></a>
By filtering, we can remove data that we are uninterested in. Here are two main ideas we can use filtering for:
- keep data that fall within a range of values to narrow our scope for visualization
- remove faulty data or outliers that skew the perception of our visualizations

As we introduced in our last workshop, the most common format to filter data is as follows:
```
table_name[table_name[column] == value] # Only keep rows with this value in the selected column
table_name[table_name[column] != value] # Only keep rows WITHOUT this value in the selected column
table_name[table_name[column] > value] # Only keep rows with greater values in the selected column
```

[Jump to Exercise 3](#ex3)

For instance, given our library traffic dataset, let's say that we want the data that only pertains to Doe Library. First, let's look at the different facilities to see how to spell "Doe Library" exactly. This is important, because without the *exact* same spelling and capitaliation, Python will not recognize what you want, and will error or return the incorrect data.

In [126]:
# one of the special functions that Series have is the `unique` function that gives all the unique values of a Series 
lib_traffic['Facility'].unique()

array([nan, 'AHC Library', 'ANTH Library', 'BANC Library', 'BIOS Library',
       'CHEM Library', 'DOE Library', 'DOE STACKS', 'EAL Library',
       'EART Library', 'ENGI Library', 'ENVI Library', 'GRDS Library',
       'HAAS Library', 'MATH Library', 'MOFF Library', 'MORR Library',
       'MUSI', 'NEWS Library', 'OPTO Library', 'PHYS Library',
       'SEAL Library', 'SOCR Library'], dtype=object)

In [128]:
# Notice that this returns an empty dataframe. Why? Because looking at the strings above, the `Doe` should be capitalized.
lib_traffic[lib_traffic['Facility'] == "Doe Library"]

Empty DataFrame
Columns: [Date-Time, Region, Facility, Entrance, Entries, Exits]
Index: []

In [129]:
# again, but with proper capitalization
doe = lib_traffic[lib_traffic['Facility'] == "DOE Library"]
doe.head()

Date-Time       Region     Facility   Entrance  Entries  Exits
8   12/11/19 12:00 AM  UC Berkeley  DOE Library  Doe North      1.0    1.0
9   12/11/19 12:00 AM  UC Berkeley  DOE Library  Doe South      3.0    2.0
39   12/11/19 1:00 AM  UC Berkeley  DOE Library  Doe North      0.0    0.0
40   12/11/19 1:00 AM  UC Berkeley  DOE Library  Doe South      3.0    3.0
70   12/11/19 2:00 AM  UC Berkeley  DOE Library  Doe North      0.0    0.0

After we narrowed our data down to Doe Library, we can see that there are two different entrances to Doe, and that there is an entry for each hour of 12/11/19. Then, there should be 24 * 2 different entries.

In [130]:
# sanity check for table size; `.shape` gives us the shape of the dataframe in the format (rows, column)
doe.shape

(48, 6)

Here's a couple of other examples of things we can do with filtering.

In [131]:
lib_traffic[lib_traffic['Entries'] > 300]

Date-Time       Region      Facility      Entrance  Entries  Exits
424  12/11/19 1:00 PM  UC Berkeley  MOFF Library  Moffit Entry    319.0    6.0
455  12/11/19 2:00 PM  UC Berkeley  MOFF Library  Moffit Entry    388.0   13.0
486  12/11/19 3:00 PM  UC Berkeley  MOFF Library  Moffit Entry    405.0    9.0

In [132]:
lib_traffic[lib_traffic['Region'] == "UC Berkeley"].head()

Date-Time       Region      Facility   Entrance  Entries  Exits
1  12/11/19 12:00 AM  UC Berkeley   AHC Library   AHC Back      0.0    0.0
2  12/11/19 12:00 AM  UC Berkeley   AHC Library  AHC Front      0.0    0.0
3  12/11/19 12:00 AM  UC Berkeley  ANTH Library       ANTH      0.0    0.0
4  12/11/19 12:00 AM  UC Berkeley  BANC Library   Bancroft      0.0    0.0
5  12/11/19 12:00 AM  UC Berkeley  BIOS Library      VLSB1      0.0    0.0

In [133]:
lib_traffic[lib_traffic['Region'] != "UC Berkeley"].head()

Date-Time Region Facility Entrance  Entries  Exits
0    12/11/19 12:00 AM    NaN      NaN     TEST      0.0    0.0
31    12/11/19 1:00 AM    NaN      NaN     TEST      0.0    0.0
62    12/11/19 2:00 AM    NaN      NaN     TEST      0.0    0.0
93    12/11/19 3:00 AM    NaN      NaN     TEST      0.0    0.0
124   12/11/19 4:00 AM    NaN      NaN     TEST      0.0    0.0

You may be wondering, what does the `NaN` mean? `NaN` is a common thing you will see with **missing/faulty data**. We won't talk about what to do with this, or how to take care of it, but just know that it is something to think about when working with a dataset.

---

You can also filter by multiple conditions by putting each condition in parentheses, and combining them with an ampersand (&). You can separate this into multiple lines, or just put it all together in the same line. For the sake of readibility, we put it in separate lines in this format example:
```
condition1 = table_name[column1] == value1
condition1 = table_name[column2] >= value2
table_name[(condition1) & (condition2)] # Only keep rows with both conditions satisfied
```

In [134]:
condition1 = lib_traffic['Exits'] > 200
condition2 = lib_traffic['Entries'] > 200
lib_traffic[(condition1) & (condition2)]

Date-Time       Region      Facility     Entrance  Entries  Exits
457  12/11/19 2:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    266.0  201.0
480  12/11/19 3:00 PM  UC Berkeley  ENGI Library         ENGI    244.0  240.0
488  12/11/19 3:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    240.0  221.0
519  12/11/19 4:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    201.0  227.0

In [138]:
# both formats work, and generate the same result!
lib_traffic[(lib_traffic['Exits'] > 200) & (lib_traffic['Entries'] > 200)]

Date-Time       Region      Facility     Entrance  Entries  Exits
457  12/11/19 2:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    266.0  201.0
480  12/11/19 3:00 PM  UC Berkeley  ENGI Library         ENGI    244.0  240.0
488  12/11/19 3:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    240.0  221.0
519  12/11/19 4:00 PM  UC Berkeley  MOFF Library  Moffitt 4th    201.0  227.0

---
Now, as a final example, let's say we are trying to find the record with the largest number of entries at Doe. We can do this in two steps.

In [141]:
# first, find the largest number in the `Entries` column
max_entries = np.max(doe['Entries'])

# then, find the row(s) that match `max_entries` in the Doe dataframe
doe[doe['Entries'] == max_entries]

Date-Time       Region     Facility   Entrance  Entries  Exits
473  12/11/19 3:00 PM  UC Berkeley  DOE Library  Doe North    243.0  185.0

From this single-record dataframe, we see that the time where there was the most entries into Doe Library on 12/11/19 was at 3pm.

In sum, using filtering, we can grab certain aspects of data that we want, and see more clearly specific points of interest. Later on, we will see how this can be useful for visualization.

## Grouping with Pandas <a class="anchor" id="grouping"></a>
By grouping, we can stratify our dataset by the unique values of a specific column in our dataset. Then, we can create visualizations based on the different stratas, and compare how they appear similar or different.

[Jump to Exercise 3](#ex3)

When we use the `groupby` function with Pandas, we will get a dataframe where:
- the column you specify to group by will become the index
- there will be 1 row for each unique value in the column
- every other column is aggregated by the function you choose

The syntax for groupby is as follows:
```
df.groupby(column).aggregation_function()
```
If we simply call `groupby` on our dataframe, it doesn't quite do anything yet. We get back a **groupby object**.

In [142]:
lib_traffic.groupby('Facility')

From here, we can then aggregate by a specific function. There are a couple of common defaults built into groupby that we'll use today.
- sum: sums all the values of each column in the group
- mean: calculated the mean of all the values of each column in the group
- min:  same as above but minimum
- max: same as above but maximum
- count: counts the number of rows in the group

For example, we can group by `Facility` in order to get the sum number of people that enter and exit each library, regardless of which entrance.

In [143]:
lib_traffic.groupby('Facility').sum()

Entries   Exits
Facility                     
AHC Library     143.0   149.0
ANTH Library    409.0   414.0
BANC Library    471.0   543.0
BIOS Library   1439.0  1438.0
CHEM Library    468.0   469.0
DOE Library    3266.0  3258.0
DOE STACKS     3221.0  3303.0
EAL Library     711.0   665.0
EART Library    257.0   266.0
ENGI Library   1932.0  1912.0
ENVI Library   1409.0  1391.0
GRDS Library    224.0   228.0
HAAS Library   1840.0  2012.0
MATH Library    433.0   440.0
MOFF Library   6996.0  6724.0
MORR Library    197.0   172.0
MUSI            575.0   574.0
NEWS Library    103.0   102.0
OPTO Library    204.0   205.0
PHYS Library    139.0   142.0
SEAL Library     71.0    72.0
SOCR Library    142.0   129.0

Notice 2 things:
1. There is 1 row for each unique facility, as expected
2. Many of the columns disappeared. Why?

We're left with only 2 columns because those are the only columns where our aggregation function, summing, makes sense. It doesn't make sense to take the sum of a bunch of strings, or of a bunch of different dates, so Pandas automatically gets rid of them. Neat!

In [144]:
lib_traffic.head()

Date-Time       Region      Facility   Entrance  Entries  Exits
0  12/11/19 12:00 AM          NaN           NaN       TEST      0.0    0.0
1  12/11/19 12:00 AM  UC Berkeley   AHC Library   AHC Back      0.0    0.0
2  12/11/19 12:00 AM  UC Berkeley   AHC Library  AHC Front      0.0    0.0
3  12/11/19 12:00 AM  UC Berkeley  ANTH Library       ANTH      0.0    0.0
4  12/11/19 12:00 AM  UC Berkeley  BANC Library   Bancroft      0.0    0.0

In [145]:
# some more examples; we add .head() to shorten the dataframe that is printed out
lib_traffic.groupby('Facility').mean().head()

Entries      Exits
Facility                          
AHC Library    2.979167   3.104167
ANTH Library  17.041667  17.250000
BANC Library  19.625000  22.625000
BIOS Library  29.979167  29.958333
CHEM Library  19.500000  19.541667

In [146]:
lib_traffic.groupby('Facility').min().head()

Date-Time       Region  Entrance  Entries  Exits
Facility                                                              
AHC Library   12/11/19 10:00 AM  UC Berkeley  AHC Back      0.0    0.0
ANTH Library  12/11/19 10:00 AM  UC Berkeley      ANTH      0.0    0.0
BANC Library  12/11/19 10:00 AM  UC Berkeley  Bancroft      0.0    0.0
BIOS Library  12/11/19 10:00 AM  UC Berkeley     VLSB1      0.0    0.0
CHEM Library  12/11/19 10:00 AM  UC Berkeley      CHEM      0.0    0.0

In [147]:
lib_traffic.groupby('Facility').max().head()

Date-Time       Region   Entrance  Entries  Exits
Facility                                                              
AHC Library   12/11/19 9:00 PM  UC Berkeley  AHC Front     17.0   15.0
ANTH Library  12/11/19 9:00 PM  UC Berkeley       ANTH     60.0   70.0
BANC Library  12/11/19 9:00 PM  UC Berkeley   Bancroft     86.0   96.0
BIOS Library  12/11/19 9:00 PM  UC Berkeley      VLSB2    108.0  110.0
CHEM Library  12/11/19 9:00 PM  UC Berkeley       CHEM     78.0   75.0

In [149]:
lib_traffic.groupby('Facility').count().head()

Date-Time  Region  Entrance  Entries  Exits
Facility                                                 
AHC Library          48      48        48       48     48
ANTH Library         24      24        24       24     24
BANC Library         24      24        24       24     24
BIOS Library         48      48        48       48     48
CHEM Library         24      24        24       24     24

One last note:

You can groupby multiple columns! This creates a multi-index table, where each unique set of column values corresponds to a row in the table. The syntax is as follows:
```
df.groupby([column1, column2]).aggregation_function()
```

Let's group by `Date-Time` and `Facility` to see the total number of people entering __each library__ at __each hour__.

In [37]:
total_lib_traffic = lib_traffic.groupby(["Date-Time", "Facility"]).sum()
total_lib_traffic

Entries  Exits
Date-Time         Facility                    
12/11/19 10:00 AM AHC Library       6.0    6.0
                  ANTH Library     24.0   14.0
                  BANC Library     29.0   47.0
                  BIOS Library     86.0   39.0
                  CHEM Library     45.0   27.0
...                                 ...    ...
12/11/19 9:00 PM  NEWS Library      0.0    0.0
                  OPTO Library      0.0    6.0
                  PHYS Library      1.0    0.0
                  SEAL Library      0.0    0.0
                  SOCR Library      0.0    1.0

[528 rows x 2 columns]

Here, the first index is all the unique date-times, and the second index is a repeated list of all the unique libraries that have a record for that date-time. So the number of rows is equal to (# unique date-times) * (# unique facilities). 

We can interpret the first row as "On 12/11/19, in the hour of 9:00am-10:00am, 6 people entered AHC Library."

#### Now we'll get into some Numpy and Pandas exercises!

## Exercise # 1 <a class="anchor" id="ex1"></a>
Calculate the minimum, maximum, average, and total number of people that entered any library.

*Hint:* We can get a NumPy array version of any column by using the [Series](#series) syntax.

In [46]:
np.min(lib_traffic['Entries'])

0.0

In [47]:
np.max(lib_traffic['Entries'])

405.0

In [48]:
np.mean(lib_traffic['Entries'])

33.13172043010753

In [49]:
np.sum(lib_traffic['Entries'])

24650.0

## Exercise #2
Calculate the net sum number of people that entered each library at each hour.

*Hint:* `net sum entered` = `Entries` - `Exits`   
*Hint2:* The sum of the resulting array should be 42.

In [54]:
lib_traffic['Entries'] - lib_traffic['Exits']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
994    NaN
995    NaN
996    NaN
997    NaN
998    NaN
Length: 999, dtype: float64

## Exercise # 3 <a class="anchor" id="ex3"></a>
Create a dataframe from `lib_traffic` that has the total number of people that enter and exit any library at each time of the day.

[Jump to Filtering Syntax](#filtering)  
[Jump to Groupby Syntax](#grouping)

In [39]:
lib_traffic.groupby('Date-Time').sum()

Entries   Exits
Date-Time                         
12/11/19 10:00 AM   1440.0   797.0
12/11/19 10:00 PM    631.0   836.0
12/11/19 11:00 AM   1710.0  1393.0
12/11/19 11:00 PM    463.0   703.0
12/11/19 12:00 AM    371.0   562.0
12/11/19 12:00 PM   2178.0  1992.0
12/11/19 1:00 AM     176.0   264.0
12/11/19 1:00 PM    2433.0  2100.0
12/11/19 2:00 AM     126.0   208.0
12/11/19 2:00 PM    2649.0  2286.0
12/11/19 3:00 AM      62.0   131.0
12/11/19 3:00 PM    2632.0  2538.0
12/11/19 4:00 AM      29.0    45.0
12/11/19 4:00 PM    2023.0  2351.0
12/11/19 5:00 AM      35.0    46.0
12/11/19 5:00 PM    1556.0  2266.0
12/11/19 6:00 AM      59.0    51.0
12/11/19 6:00 PM    1329.0  1830.0
12/11/19 7:00 AM     104.0    81.0
12/11/19 7:00 PM    1058.0  1354.0
12/11/19 8:00 AM     349.0   130.0
12/11/19 8:00 PM    1025.0  1057.0
12/11/19 9:00 AM    1279.0   501.0
12/11/19 9:00 PM     933.0  1086.0

## Exercise #4
Create the same dataframe as above, but instead of any library, look only at the Engineering Library.

In [42]:
eng_lib_traffic = lib_traffic[lib_traffic['Facility'] == 'ENGI Library']
eng_lib_traffic.groupby('Date-Time').sum()

Entries  Exits
Date-Time                        
12/11/19 10:00 AM     87.0   24.0
12/11/19 10:00 PM     70.0   80.0
12/11/19 11:00 AM    123.0   99.0
12/11/19 11:00 PM     24.0   97.0
12/11/19 12:00 AM      4.0   71.0
12/11/19 12:00 PM    133.0  112.0
12/11/19 1:00 AM       0.0    0.0
12/11/19 1:00 PM     177.0  138.0
12/11/19 2:00 AM       0.0    0.0
12/11/19 2:00 PM     245.0  154.0
12/11/19 3:00 AM       0.0    0.0
12/11/19 3:00 PM     244.0  240.0
12/11/19 4:00 AM       0.0    0.0
12/11/19 4:00 PM     181.0  189.0
12/11/19 5:00 AM       0.0    0.0
12/11/19 5:00 PM     147.0  210.0
12/11/19 6:00 AM       0.0    0.0
12/11/19 6:00 PM     120.0  160.0
12/11/19 7:00 AM       0.0    0.0
12/11/19 7:00 PM     107.0  123.0
12/11/19 8:00 AM       2.0    4.0
12/11/19 8:00 PM     109.0   76.0
12/11/19 9:00 AM      51.0   14.0
12/11/19 9:00 PM     108.0  121.0

## Exercise # 5
Create a dataframe that has the maximum number of people that enter and exit each entrance. 

In [44]:
lib_traffic.groupby('Entrance').max()

Date-Time       Region      Facility  Entries  Exits
Entrance                                                                    
AHC Back         12/11/19 9:00 PM  UC Berkeley   AHC Library     10.0    9.0
AHC Front        12/11/19 9:00 PM  UC Berkeley   AHC Library     17.0   15.0
ANTH             12/11/19 9:00 PM  UC Berkeley  ANTH Library     60.0   70.0
Bancroft         12/11/19 9:00 PM  UC Berkeley  BANC Library     86.0   96.0
CHEM             12/11/19 9:00 PM  UC Berkeley  CHEM Library     78.0   75.0
Doe North        12/11/19 9:00 PM  UC Berkeley   DOE Library    243.0  235.0
Doe South        12/11/19 9:00 PM  UC Berkeley   DOE Library    158.0  186.0
EAL              12/11/19 9:00 PM  UC Berkeley   EAL Library     94.0   72.0
ENGI             12/11/19 9:00 PM  UC Berkeley  ENGI Library    245.0  240.0
ENVI             12/11/19 9:00 PM  UC Berkeley  ENVI Library    152.0  144.0
Earth North      12/11/19 9:00 PM  UC Berkeley  EART Library     26.0   22.0
Earth South      12/11/19 9:00 PM  UC Berkeley  EART Library     17.0   22.0
GRAD             12/11/19 9:00 PM  UC Berkeley  GRDS Library     39.0   30.0
HAAS 2F          12/11/19 9:00 PM  UC Berkeley  HAAS Library    148.0  137.0
HAAS 3F          12/11/19 9:00 PM  UC Berkeley  HAAS Library     67.0   80.0
MATH             12/11/19 9:00 PM  UC Berkeley  MATH Library     60.0   68.0
MUSI             12/11/19 9:00 PM  UC Berkeley          MUSI     94.0   73.0
Moffit Corridor  12/11/19 9:00 PM  UC Berkeley    DOE STACKS    196.0  205.0
Moffit Entry     12/11/19 9:00 PM  UC Berkeley  MOFF Library    405.0   13.0
Moffit Exit      12/11/19 9:00 PM  UC Berkeley  MOFF Library      3.0  300.0
Moffitt 4th      12/11/19 9:00 PM  UC Berkeley  MOFF Library    300.0  227.0
Morrison         12/11/19 9:00 PM  UC Berkeley  MORR Library     37.0   36.0
News             12/11/19 9:00 PM  UC Berkeley  NEWS Library     16.0   16.0
OPTO             12/11/19 9:00 PM  UC Berkeley  OPTO Library     36.0   41.0
PHYS             12/11/19 9:00 PM  UC Berkeley  PHYS Library     21.0   26.0
SEAL             12/11/19 9:00 PM  UC Berkeley  SEAL Library     15.0   14.0
SOCR             12/11/19 9:00 PM  UC Berkeley  SOCR Library     26.0   22.0
Stacks East      12/11/19 9:00 PM  UC Berkeley    DOE STACKS    112.0  145.0
TEST             12/11/19 9:00 PM          NaN           NaN      0.0    0.0
VLSB1            12/11/19 9:00 PM  UC Berkeley  BIOS Library    106.0  110.0
VLSB2            12/11/19 9:00 PM  UC Berkeley  BIOS Library    108.0   74.0

# BREAK

## Best Practices For Creating Visualizations

What exactly is a visualization?


Visualization is the visual representatino of information to:

    Aid understanding
    Explain and explore
    Reinforce cognition
    
    
 Why do we visualize?

    For analysis! 
    To Provide insight on data beyond descriptive statitics 
    Use Visual system to understand information that is not as well expressed in a different medium
    Tranform visual presentation for new understanding
    

Lets Talk Affordances!

Affordances:

    The aspects inherent to a design that imply how is to be used 
    
How can we apply this to visualizations?

Lets look at some examples!

<div>
<img src="images/pet pref by gender 1.png" width="400" style="float:center"/>
</div>

Whats wrong with this visualization? 

Lets Break it down

    1. The Lines are too thin
    2. The Lines are not labeled, and you must look at the legend and back at the line to understand what each color represents 
    3. The colors do not add any significance
    4. The Y-Axis is not even labeled
    5. Data is to concentrated in the middle, lots of white space along both sides

<div>
<img src="images/pet pref by gender 2.png" width="400" style="float:center"/>
</div>

This new visualization is much better.

Lets break down the differences.

    1. Line are thicker 
    2. Labels appear on the line, rather than a legend, makes it easier and faster to read
    3. Colors now have signifance, Cats/Dogs are visually different, while both is a combination of those two colors. Neither is a nuetral grey. 
    4. Y-Axis now reads: Percent Male v Female

    



### Pie Charts

Pie charts are poor at communicating data. 

The amount of space they take compared to the story its trying to tell. 


The human brain is not very good at copmaring the size of angles and because theres no scale, reading accurate values can be diffucult. 

Lets Take a Look.

<div>
<img src="images/bad pie.png" width="400" style="float:center"/>
</div>

In this example, the company is trying to show conceptually adjacent values, in a more categorical format. 

In simpler terms, the scale of Not at all interested to Extremely interested is not taken into account, even though that scale should be a valueable asset in communicating the findings. 

## Plotting with Matplotlib

In [49]:
lib_traffic.head()

#groupby facility, plot timeline during a given day, another plot for entire semester 

Date-Time       Region      Facility   Entrance  Entries  Exits
0  12/11/19 12:00 AM          NaN           NaN       TEST      0.0    0.0
1  12/11/19 12:00 AM  UC Berkeley   AHC Library   AHC Back      0.0    0.0
2  12/11/19 12:00 AM  UC Berkeley   AHC Library  AHC Front      0.0    0.0
3  12/11/19 12:00 AM  UC Berkeley  ANTH Library       ANTH      0.0    0.0
4  12/11/19 12:00 AM  UC Berkeley  BANC Library   Bancroft      0.0    0.0

## Exercise #1

##  Exercise #2

## Plotting with Seaborn

## Exercise  #1