In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
import numpy as np

# **Welcome to the Kresge Library's Introduction to Data Visualization**
### **By Vincent Lao and Daniel del Carpio**
##### In Collaboration with the Division of Data Science's [Data Peer Consulting](https://data.berkeley.edu/ds-peer-consulting)

# Vincent Lao 
![Richa](https://data.berkeley.edu/sites/default/files/styles/width_400/public/richa_-_richa_bhattacharya.jpg?itok=Mr7ME_3R&timestamp=1599264242)

Quick Facts About Me:

    🐻 Junior at Cal
    🎒 Studying Computer Science, Data Science
    👨🏼‍🏫 Academic Intern for CS61A and CS61B
    🏢 Previously interned at American Express
    📊 Joined the Data Peer Consulting team in Fall 2019

How to Reach/Stalk Me:

    📮 Email: richa.b@berkeley.edu
    👨🏼‍💻 Github: @richab2000

# Daniel del Carpio
![Carlos](https://data.berkeley.edu/sites/default/files/styles/width_400/public/img_3245_-_carlos_ortega.jpeg?itok=6cdS9XWS&timestamp=1599261924)
Quick Facts About Me:

    🐻 Senior at Cal
    🎒 Studying Cognitive Science, interest in NLP
    👨🏼‍🏫 I love to teach
    🏢 Previously worked for U.S. Census Bureau, ICSI, Data 8 Course Staff
    📊 Joined the Data Peer Consulting team in Fall '18

How to Reach/Stalk Me:

    📮 Email: ceos@berkeley.edu
    👨🏼‍💻 Github: @SoyCarlos

## Summary of Last Workshop 

# What is Numpy?

![Python Logo](images/python-logo.png)

From [Python's Official Site](https://www.python.org/doc/essays/blurb/):


> Python is an **interpreted**, **object-oriented**, **high-level programming language** with dynamic semantics. Its high-level built in data structures, combined with **dynamic typing** and **dynamic binding**, make it very attractive for **Rapid Application Development**, as well as for use as a **scripting** or glue language to connect existing components together. Python's simple, **easy to learn syntax** emphasizes **readability** and therefore reduces the cost of program maintenance. Python supports **modules** and **packages**, which encourages program modularity and code reuse. The Python interpreter and the extensive standard library are available in source or binary form without charge for all major platforms, and can be freely distributed. 

In layman terms, Python is:
- A Programming Language
- Easy to read
- Easy to learn
- Easy to use with other pre-existing programs
- Quick to adapt to any use-cases
- Open-Source

Modules, packages, and libraries are collections of re-usable code used to improve the interoperability of code and the effiency of programmers.

Examples:
- [Pandas](https://pandas.pydata.org/) - Today's package of choice for data analysis
- [Numpy](https://numpy.org/) - Scientific Computing
- [Biopython](https://biopython.org/) - Biological Computation
- [Astropy](https://www.astropy.org/index.html) - Astronomy
- [Nilearn](http://nilearn.github.io/) - Neuroimaging
- [SageMath](https://www.sagemath.org/) - Collection of Math Packages (Elementary, Algebra, Calculus, Number Theory, etc)


### Reference Sheets for today!
Links updated as of 9/29/20  
- [NumPy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)  
- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)  
- [Matplotlib Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Matplotlib_Cheat_Sheet.pdf)  
- [Seaborn Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Seaborn_Cheat_Sheet.pdf)

# NumPy Fundamentals
NumPy stands for "Numerical Python". What this means is that Numpy is a package used for fast, efficient numerical calculations in Python. Numpy uses what we will call ***Numpy Arrays***, which are very similar to Python lists, but have a couple of key differences that we will take a look at.  

To use the Numpy package, we must always import it into whatever text editor (program used for coding, e.g. Jupyter Notebook) that we are using.

In [4]:
# the conventional NumPy import statement
import numpy as np

We can now use the NumPy package with the shorthand `np`! We access various functions inside this package with `np.function(*arguments)`, where function() is the function you would like to use.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Without further ado, let's talk about the differences between NumPy arrays and Python lists!  

---

**Key Difference 1:** They have different data types.

In [2]:
# Python list
# The notation to create one is using square brackets. You can create an empty one like so:
list1 = []
type(list1)

list

In [10]:
# Numpy array
# Notice that by passing a Python list into the np.array() function as an argument, it turns it into a NumPy array!
array1 = np.array([])
type(array1)

numpy.ndarray

**Key Difference 2:** Python lists can contain any kind of data type, and keeps them the way they are. However, NumPy objects can only contain data of the same type.

In [12]:
list2 = ['any', 123, 'kind', 456, 'of', 123/456, 'data', True, 'type']
list2

['any', 123, 'kind', 456, 'of', 0.26973684210526316, 'data', True, 'type']

In [15]:
array2 = np.array(list2)
array2

array(['any', '123', 'kind', '456', 'of', '0.26973684210526316', 'data',
       'True', 'type'], dtype='<U19')

In [20]:
array2[1], list2[1]

('123', 123)

In [21]:
type(array2[1]), type(list2[1])

(numpy.str_, int)

How does NumPy determine which data type to turn everything into then? 

Out of the primitive* data types, there's a "data type hierarchy" so to speak. NumPy will turn all the entries into the most complex data type that it finds in the array. The hierarchy is as follows, from least complex to most complex:
- **Boolean < Integer < Float < String**

\**primitive data types: boolean - true/false, integer, float - decimal numbers, string - letters*

In [23]:
# some more examples
np.array([True, False, 1, 2, 3, 1.1, 2.2, 3.3]), np.array([True, False, 1, 2, 3])

(array([1. , 0. , 1. , 2. , 3. , 1.1, 2.2, 3.3]), array([1, 0, 1, 2, 3]))

- True values turn into 1
- False values turn into 0
- Integers get a decimal point
- Floats turn into strings, indicated by the quotation marks around them

**Key Difference 3 [Very Important] :** Numerical operations with Python lists has different behavior than adding NumPy arrays.

In [24]:
list3 = [1, 2, 3]
list4 = [1, 2, 3]
list3 + list4

[1, 2, 3, 1, 2, 3]

In [26]:
list3 - list4 # error is expected

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [31]:
list3 * list4 # error is expected

TypeError: can't multiply sequence by non-int of type 'list'

In [32]:
list3 / list4 # error is expected

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [34]:
# What if we put strings inside the Python lists?
string_list1 = ['test', '1', '2', '3']
string_list2 = ['test', '4', '5', '6']
string_list1 + string_list2

['test', '1', '2', '3', 'test', '4', '5', '6']

In [25]:
array3 = np.array(list3) # Q: What is happening here? A: Think about replacing "list3" with the value assigned to it!
array4 = np.array(list4)
array3 + array4

array([2, 4, 6])

In [27]:
array3 - array4

array([0, 0, 0])

In [29]:
array3 * array4

array([1, 4, 9])

In [30]:
array3 / array4 # notice it automatically converts things to floats when we divide!

array([1., 1., 1.])

In [35]:
array3 ** array4 # ** denotes exponents, which also works for NumPy!

array([ 1,  4, 27], dtype=int32)

In [33]:
# What if we put strings inside the NumPy arrays?
string_array1 = np.array(['test', '1', '2', '3'])
string_array2 = np.array(['test', '4', '5', '6'])
string_array1 + string_array2

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U4') dtype('<U4') dtype('<U4')

In short, there are some limitations to both. 
- Python lists can hold multiple data types at a time, while NumPy can only hold one data type at a time
- Adding Python lists *concatenates* them, while adding NumPy arrays performs element-wise addition
- Other operations on Python lists don't work, but any numerical operation works element-wise with NumPy arrays

---

Now, let's learn some very common NumPy array functions besides `np.array()`!

### Commonly Used NumPy Functions
Here is the corresponding NumPy documentation for reference:
- [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
- [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)
- 

Alternatively, when your typing line is hovering over a function, you can click `shift` + `tab` to open up the same documentation in Jupyter Notebook. Handy!

`np.arange` creates a list of numbers based on the arguments you pass in.

In [36]:
# np.arange(start value, stop value, step size); stop value is not included!
# default start is 0, stop value is required (no default), default step size is 1 
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [40]:
np.arange(0,5,2)

array([0, 2, 4])

In [41]:
np.arange(2,6,2) # Before running this, try to predict what it will print out!

array([2, 4])

---

`np.linspace` creates a list of `n` values that are perfectly evenly spaced between `start value` and `stop values`, where `n = number of values`.

This is very handy for when you need to create visualizations, and you want your tick marks or bins to be perfectly spaced.

In [45]:
# np.linspace(start value, stop value, number of values)
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [48]:
# "number of values" has a default of 50
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

---

There are many functions that calculate various descriptive statistics as well. Note that you can pass in either a NumPy array or a Python list, as its argument.

- np.min
- np.max
- np.sum
- np.mean
- np.median
- np.std
- np.percentile

In [51]:
numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
np.min(numbers), np.max(numbers), np.sum(numbers)

(1, 233, 609)

In [55]:
np.mean(numbers), np.std(numbers), np.median(numbers), np.percentile(numbers, 50) # 50th percentile = median

(46.84615384615385, 67.54582052075824, 13.0, 13.0)

## Pandas Fundamentals 

## Exercise # 1

## Exercise # 2

## Exercise # 3

# BREAK

## Best Practices For Creating Visualizations

## Exercise # 1

## Exercise # 2

## Plotting with Matplotlib

## Exercise #1

##  Exercise #2

## Plotting with Seaborn

## Exercise  #1